### ISSUE TITLE
Update the README to explain what argo-links is and why you need it

### ISSUE THREAD

**Issue by willhaynes** [INN/link-roundups#1]
_From @rnagle on June 8, 2015 14:42_

_Copied from original issue: INN/argo-links#30_

**Comment by willhaynes** [comment]
_From @rnagle on June 8, 2015 14:47_

Probably add a `README.md` for documentation. `README.txt` is required for submitting to the WordPress plugin repo and doesn't get parsed/rendered by Github as `.md` files do.

**Comment by aschweigert** [comment]
addressed in #67
