### ISSUE TITLE
Typo in widget query args

### ISSUE THREAD

**Issue by benlk** [INN/link-roundups#102]
https://github.com/INN/link-roundups/blob/master/inc/lroundups/widget.php#L28 misspells 'excerpt' in the query. 

Oddly, 'excerpt' is not a listed option on `WP_Query`: https://codex.wordpress.org/Class_Reference/WP_Query

**Comment by aschweigert** [comment]
sooo....that should probably just be removed?

**Comment by benlk** [comment]
Talked it over with David, it appears safe to remove.
