### ISSUE TITLE
Saved Links Widget Title Doesn't Work w/ Largo Widget Title URL Func

### ISSUE THREAD

**Issue by 0aveRyan** [INN/link-roundups#104]
Here's how Largo makes widget title's links and applies these fields to all widgets regardless of origin (largo, wp, 3rd party plugin, etc):
https://github.com/INN/Largo/blob/f4ddf0b27b5fc34fb826e7ac22a9c393b4cbed1a/inc/widgets.php#L211-L223

Here's where link-roundups passes the `title` arg (native) and `title_link` (largo) with filter:
https://github.com/INN/link-roundups/blob/master/inc/saved-links/widget.php#L17

**Comment by joshdarby** [comment]
@benlk This is ready to be looked at in #152.
