### ISSUE TITLE
Move MAILCHIMP.md to the docs directory, add a link to README.md

### ISSUE THREAD

**Issue by rnagle** [INN/link-roundups#11]
As the title says.

`MAILCHIMP.md` belongs in the docs directory.

**Comment by aschweigert** [comment]
https://github.com/INN/link-roundups/blob/master/docs/mailchimp.md exists, just need to consolidate https://github.com/INN/link-roundups/blob/master/MAILCHIMP.md into it.

**Comment by aschweigert** [comment]
covered in #67
