### ISSUE TITLE
Link Roundups widget displays same roundups several times 

### ISSUE THREAD

**Issue by jackbrighton** [INN/link-roundups#112]
Testing the Link Roundups widget on several Largo sites, it seems that when Number of posts to show is greater than 1, the widget displays the same roundups more than once. The widget was tested in the sidebar of several Largo staging sites:

Example from the Iowawatch staging site:

![link-roundups-widget-iowawatch-staging](https://cloud.githubusercontent.com/assets/506788/15085523/71b651cc-13a0-11e6-897e-dd301b19eda0.png)

From Youth Today staging site:
![link-roundups-widget-youthtoday-staging](https://cloud.githubusercontent.com/assets/506788/15085528/7e42dec4-13a0-11e6-98d2-e1c4a3d27d73.png)

GIJN staging site:
![link-roundups-widget-gijn-staging](https://cloud.githubusercontent.com/assets/506788/15085538/8962e0a6-13a0-11e6-87e4-722aa06281ed.png)

Largo Demo Site:
![link-roundups-widget-in-sidebar-largo-test-site](https://cloud.githubusercontent.com/assets/506788/15085544/917f24a2-13a0-11e6-8736-63c41441db89.png)

**Comment by benlk** [comment]
Confirmed, displays many when set to display only 5:

![Screen Shot 2019-05-10 at 19 18 57 ](https://user-images.githubusercontent.com/1754187/57561274-c7540780-7358-11e9-9c43-9b248ca941f3.png)
