### ISSUE TITLE
Stable releases with dependencies included via git or composer need all-in-one download .zip files

### ISSUE THREAD

**Issue by benlk** [INN/link-roundups#115]
We can upload build zip file to GitHub: https://github.com/blog/1547-release-your-software

They would appear at https://github.com/INN/link-roundups/releases

**Comment by rnagle** [comment]
With the new `release.sh` this can be accomplished by running `./release.sh --dry_run` from the root of the project. Once the command finishes, you'll have a `release/wp-release.zip` file that you can uploade to Github.
