### ISSUE TITLE
rss feed for rounduplinks post type is busted

### ISSUE THREAD

**Issue by aschweigert** [INN/link-roundups#120]
Observed on: 

http://midwestenergynews.com/rounduplink/feed/
http://womensenews.org/rounduplink/feed/
etc.

This is just showing the recent posts (of any post type or just posts?) from the site instead of saved links. Tried resetting permalinks, dumping the cache, etc. to no avail so this is probably a bug introduced in the most recent update.

This is an urgent issue for Women's eNews because their daily newsletter relies on this feed and is currently busted (again, probably since we updated our copy of the plugins on production)

**Comment by benlk** [comment]
Where did the `/rounduplink/feed/` URL come from?

The feed at the url http://womensenews.org/feed/?post_type=rounduplink is also not reflecting the most-recent posts.

This apparently has worked in the past, but as far as I can tell no commit has introduced or removed the strings `rss` or `feed` in a non-documentation context.

**Comment by aschweigert** [comment]
No idea but it was definitely working before that last plugin update on production. The merge tag in mailchimp looks like this: 

*|FEEDBLOCK:http://womensenews.org/rounduplink/feed|* *|FEEDITEMS:[$count=3]|*
*|FEEDITEM:TITLE|*
(*|FEEDITEM:AUTHOR|*)
*|END:FEEDITEMS|* *|END:FEEDBLOCK|*

so it was definitely working until it wasn't. which seems to have coincided precisely with that last update.

**Comment by benlk** [comment]
Introduced in v0.4.0: https://github.com/INN/link-roundups/commit/3043bb56d2fcf294b6c01d186f2aea99ea9292d1#comments

```php
'public' 		=> current_user_can( apply_filters( 'link_roundups_minimum_capability', 'edit_posts' ) ) ? true : false,
```

If a user's logged out, then the value of `public` in the [register_post_type](https://codex.wordpress.org/Function_Reference/register_post_type) call is `false`, and so it's not publicly queryable, and so there's no RSS feed for it.

I'm going to change 'public' to True, based on this comment: https://github.com/INN/link-roundups/commit/3043bb56d2fcf294b6c01d186f2aea99ea9292d1#commitcomment-17179384

And that'll solve the problem.
