### ISSUE TITLE
"Send links to the editor" experiences problem.

### ISSUE THREAD

**Issue by donpogreba** [INN/link-roundups#127]
When I try to "Send links to the editor" the page refreshes and does not add any links to the editing window. Replicated on multiple browsers

**Comment by benlk** [comment]
This sounds like some javascript isn't loaded correctly. @donpogreba I know it's been 15 months since you filed this issue, but can you still reproduce it?

**Comment by benlk** [comment]
Looking at WordPress' version history, February 2017 would've been 4.7.2 or earlier.

**Comment by benlk** [comment]
I haven't had this problem in 5.2-RC2/ :/

**Comment by benlk** [comment]
Confirmed; set to display 5 it displays many: 
![Screen Shot 2019-05-10 at 19 18 57 ](https://user-images.githubusercontent.com/1754187/57561233-85c35c80-7358-11e9-8a00-b429c5143014.png)

**Comment by benlk** [comment]
Unable to replicate.
