### ISSUE TITLE
Dateline format in the mailchimp campaigns

### ISSUE THREAD

**Issue by kaeti** [INN/link-roundups#14]
It currently generates a date like "2015-05-28 09:47:54"

Would be good to have that in a readable format for the campaigns.   "July 6, 2015" or something

**Comment by kaeti** [comment]
Status on this?

**Comment by willhaynes** [comment]
Ryan and I pushed a fix for this [on master](https://github.com/INN/link-roundups/commit/e351ee77de6904c975a01b81d1b39f67620affa5) a few days ago. Uses the built in WordPress date format defined in site settings.
