### ISSUE TITLE
Should the next version be 1.0 instead of 0.5?

### ISSUE THREAD

**Issue by benlk** [INN/link-roundups#148]
How strongly do we want to stick to semantic versioning? https://semver.org/

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> 
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

Arguments in favor of bumping plugin version to 1.0:

- the email template changes described in https://github.com/INN/link-roundups/pull/139#issuecomment-490283205
- The "Press this" bookmarklet functionality for saving things in WordPress was removed in WordPress 4.9; as a result this plugin's corresponding feature stopped working. https://github.com/INN/link-roundups/issues/130

Arguments against:

- the email functionality has been broken for three-plus years; no one's still using it that would be affected by this change.
- the core features of this plugin aren't changed: Link Roundup posts and Saved Links posts are still present

**Comment by kaylima** [comment]
I vote yes to 1.0, as it should already be _at least_ 1.0:

```
How do I know when to release 1.0.0?
If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.
```

**Comment by benlk** [comment]
Bumped to 1.0.
