### ISSUE TITLE
If MailChimp campaign doesn't exist, remove "Edit in MailChimp" link from post editor

### ISSUE THREAD

**Issue by kaeti** [INN/link-roundups#15]
_From @rnagle on May 12, 2015 18:23_

If a campaign has been created via WordPress and deleted via MailChimp's dashboard, the "Edit..." link will still appear, but result in an error once you land on MailChimp.

For the time being, the workaround is to delete the `mc_web_id` custom field from the roundup post and reload the post editor page.

As for a solution, I know that I don't like the idea of checking the web id validity every time the post editor page loads. I'd rather intercept the click on the "Edit..." button and check the campaign at that point, delivering an error message to the user and handling removal of the `mc_web_id` automatically.

_Copied from original issue: INN/argo-links#27_

**Comment by kaeti** [comment]
An idea Ryan and I discussed would be to include a secondary link under the "Edit in Mailchimp" link that says something like "Regenerate campaign" or "start over and create a new/another mailchimp campaign." That would create another campaign in MailChimp from the same WordPress post (and the edit in mailchimp link would then link to the new campaign).

This is just one idea.

**Comment by rnagle** [comment]
Fixed in c6b611eb890dc0166b98ebbdae12578d07322a56.
