### ISSUE TITLE
Repect published permalinks.

### ISSUE THREAD

**Issue by willhaynes** [INN/link-roundups#2]
_From @willhaynes on June 18, 2015 15:54_

Since we're changing post types the default slugs for roundups are going to change. But we probably shouldn't change any sites URLs for published roundups.

So: On update to 0.3, if a user has not specified a custom `argo_link_roundups_custom_url` option, we should update it to `argolinkroundups`. This should leave their URLs intact unless they choose to change it.

Bonus points to check that there are indeed published roundups first.

_Copied from original issue: INN/argo-links#41_

**Comment by benlk** [comment]
4 years old, from the Argo Links -> Link Roundups transition.
