### ISSUE TITLE
Add prompt (or automate) saving of WordPress Permalink Settings when changing URL slug

### ISSUE THREAD

**Issue by dryanmedia** [INN/link-roundups#20]
When saving the URL slug, URLs break unless Permalink settings are updated. We should prompt or automate this.

**Comment by aschweigert** [comment]
patch will be in PR #41

**Comment by dryanmedia** [comment]
This is actually hard because the function doesn't work as advertised. 

Likely an issue with priorities and needing to be called somewhere earlier than the options area we're trying to hook it into.

Hoping to iron out using AJAX to hit the current rewrite page and reset permalinks, return a response. But for another day.

**Comment by dryanmedia** [comment]
https://github.com/INN/link-roundups/tree/flush-permalinks

**Comment by rnagle** [comment]
@dryanmedia I think you're onto something regarding the timing and priority here. Maybe we can use one of the [rewrite filters](https://codex.wordpress.org/Plugin_API/Filter_Reference#Redirect.2FRewrite_Filters) to make sure this is set up properly?

Just a thought for once we have time to take a second look at this issue.

**Comment by dryanmedia** [comment]
In #74
