### ISSUE TITLE
Argo Link This! button should be named after the site

### ISSUE THREAD

**Issue by aschweigert** [INN/link-roundups#28]
@benlk said:

In the occasion that someone is running multiple ALT! buttons, thy should be able to tell the difference between different ALT! buttons, whether it be from the favicon on the button or the name on the button.

This is probably as simple as changing the text in the button tag that is served to users.

Moved from: https://github.com/INN/argo-links/issues/25

**Comment by dryanmedia** [comment]
Spent some time on this today it's mostly closed out but opened new related issue #38 for 0.3.1 release.

**Comment by dryanmedia** [comment]
Can be found in ```add-sing-plural-FE-135``` branch

**Comment by aschweigert** [comment]
Patch in #41
