### ISSUE TITLE
if link roundups are a collection of links, shouldn't they be...a collection of links?

### ISSUE THREAD

**Issue by willhaynes** [INN/link-roundups#3]
_From @aschweigert on February 16, 2015 15:52_

Right now the link roundups are created by dumping the links (with description, etc.) directly into the body of a new post, instead maybe they ought to be more like "collections" (similar to how galleries are a collection of photos) where we preserve the reference to the original links, make them discrete, shareable units, etc.

_Copied from original issue: INN/argo-links#13_

**Comment by aschweigert** [comment]
ok to close...i think? anything we still need to do here?

**Comment by aschweigert** [comment]
store IDs in a way that does not require querying the entire post/parsing the content
