### ISSUE TITLE
Document difference between "Save Draft" and "Publish" buttons in Argo Link This!

### ISSUE THREAD

**Issue by aschweigert** [INN/link-roundups#32]
moved from https://github.com/INN/argo-links/issues/19

**Comment by benlk** [comment]
Publish: appears in the archive, available to add to roundup

Save: Available to add to roundup? What happens if it's saved as a draft but not published?

**Comment by aschweigert** [comment]
- [ ] what happens in roundups if a link is included but not published?
- [ ] explain where published links appear (in widget, archive page for the post type, etc.)
- [ ] what is the purpose of a draft link? when would someone want to do this? Can these buttons just be consolidated?

**Comment by benlk** [comment]
Using #41's code, it looks like draft posts show up in the editor. Is this intentional?

**Comment by benlk** [comment]
- draft links included in published roundups are visible, even if you're not logged in
- draft links appear in the roundup post editor
- it's unclear what actual use drafts have, so I'm in favor of removing the draft if possible.

Maybe drafts will have some significance if people use Edit Flow or some other plugin, but right now it's a semantic difference and not a functional difference.

**Comment by benlk** [comment]
- [ ] Remove "Save Draft" button on Save Link button editor
