### ISSUE TITLE
Submit to WP plugin directory

### ISSUE THREAD

**Issue by willhaynes** [INN/link-roundups#4]
_From @aschweigert on March 19, 2014 22:34_

_Copied from original issue: INN/argo-links#4_

**Comment by willhaynes** [comment]
_From @aschweigert on May 7, 2015 21:59_

Let's also call this something other than argolinks. Credit the original creators in the readme similar to what documentcloud just did. But let's call it something more descriptive and likely to get it found/used when we submit it. Any ideas? @benlk @rnagle

**Comment by willhaynes** [comment]
_From @benlk on May 12, 2015 18:26_

Link Roundups (With MailChimp)

**Comment by willhaynes** [comment]
_From @benlk on June 6, 2015 1:16_

Do we have any suggestions for names other than "Argo Links"?

**Comment by willhaynes** [comment]
_From @benlk on June 6, 2015 1:17_

@willhaynes Were you working on a script or documentation on how to submit things to the WordPress plugin directory?

**Comment by willhaynes** [comment]
Yep. There's a script.

First though we need to [submit the plugin to the WordPress](https://wordpress.org/plugins/add/) to get an svn endpoint to push to.

That process involves submitting a name for the plugin. After this the name cannot change. The plugin will live at `wordpress.org/plugins/plugin-name` and `wp-content/plugins/plugin-name/`

With that, I think we should consider what we want this thing to be named. First, with the Argo project sunset, it could be confusing having "Argo" in an active product name. Second, "Argo Links" doesn't really say anything about what the plugin actually _does_, which I think is incredibly important to how people browse the plugin directory.

I don't have any great ideas on what to suggest instead, but I think that "Link Roundup" is generally more descriptive. We could replace Argo with Largo too, although I worry that might indicate that it requires Largo or a child theme (which I believe is not true).

@rnagle, @aschweigert thoughts? (@benlk too, if he has thoughts from the road)

**Comment by willhaynes** [comment]
_From @rnagle on June 8, 2015 16:25_

I agree a more descriptive name would be better. Maybe something like "Link Roundup Curator" or "Link Roundup Aggregator" -- something to indicate this is meant to help assemble a bunch of links from elsewhere on the interwebs for you to post on your site.

We can also add tags and such to the `readme.txt` we submit to wordpress.org. That should help the plugin find its way to folks that want to use it.

**Comment by willhaynes** [comment]
_From @aschweigert on June 8, 2015 21:17_

i think something like "link roundups" would probably be ok...i'll think about it a bit. we should definitely lose the argo prefix though and i'm not wild about using largo as a replacement. probably just stick with a more descriptive (and brief) name if possible.

**Comment by willhaynes** [comment]
Any additional thoughts here, @aschweigert @rnagle?

**Comment by willhaynes** [comment]
_From @aschweigert on June 15, 2015 14:20_

Link Roundup (or something similar) is fine with me

**Comment by aschweigert** [comment]
- [ ] wordpress.org account
- [ ] readme.txt
- [ ] request svn repo

**Comment by rnagle** [comment]
Done: https://wordpress.org/plugins/links-roundups/
