### ISSUE TITLE
Settings to be migrated

### ISSUE THREAD

**Issue by dryanmedia** [INN/link-roundups#42]
Going to focus on other tickets before jumping into this one. Have left all settings with their argo-* cruft intact.

**This could theoretically hold off until 0.3.1**, but would be very nice to fit into 0.3.0 so I'm putting it in that milestone for now.

We'll need to migrate the following settings using something similar to what Will wrote here:
https://github.com/INN/link-roundups/blob/master/inc/lroundups-update-functions.php#L24

#### Saved Links

* argo_link_url --> rounduplink_url
* argo_link_description --> rounduplink_description
* argo_link_source --> rounduplink_source
* argo_link_img_url --> rounduplink_img_url

##### Saved Links Taxonomy

* argo-link-tags --> rounduplink_tags

#### Link Roundups 
``` php 
// register our settings
		register_setting('argolinkroundups-settings-group', 'argo_link_roundups_custom_url');
		register_setting('argolinkroundups-settings-group', 'argo_link_roundups_custom_html');
		register_setting('argolinkroundups-settings-group', 'argo_link_roundups_sponsored_style');
		register_setting(
			'argolinkroundups-settings-group', 'link_roundups_custom_name_singular'
		);
		register_setting(
			'argolinkroundups-settings-group', 'link_roundups_custom_name_plural'
		);
		register_setting(
			'argolinkroundups-settings-group', 'argo_link_roundups_use_mailchimp_integration',
			array(__CLASS__, 'validate_mailchimp_integration')
		);
		register_setting('argolinkroundups-settings-group', 'argo_link_roundups_mailchimp_api_key');
		register_setting('argolinkroundups-settings-group', 'argo_link_mailchimp_template');
		register_setting('argolinkroundups-settings-group', 'argo_link_mailchimp_list');
```

**Comment by rnagle** [comment]
The settings migration is done in f3f0881e881cf1ece99106e7c053d8350476e38a.

@dryanmedia [notes here](https://github.com/INN/link-roundups/issues/8#issuecomment-126803733) what is left to completely purge "argo" from the plugin. We'll take care of those items over the next few releases.
