### ISSUE TITLE
for saved links, ability to insert links in description (instead of using headline)

### ISSUE THREAD

**Issue by aschweigert** [INN/link-roundups#51]
Note from Ken at Midwest Energy News:

1. Do not display the link title (but keep it for admin purposes)
2. A function that easily allows the link to be embedded in the text. I’ve done it manually with HTML here: http://midwestenergynews.com/wp-admin/post.php?post=72893&action=edit. Would like to be able to highlight the link text, click a button and have it insert the URL.
3. Use tags (or some other variable) to display a header in place of where “Title” is going now, replaced with a bulleted list if more than one item is grouped under the same tag (realizing this last bit may be easier said than done).
4. Offset the source a bit more and add parentheses.

So we’d have:
[TAG]: description description description [URL with link text] description description description. ([SOURCE])

Failing that, a more scaled back approach would be to stick with the Headline/Description format and allow the links to be single spaced and flush left (instead of indented) within the digest.

Other than the third point in his list, this seems reasonable to me. Basically we'd want to give people a way to add a link in the description text instead of the link always being the headline.

I'll probably make a separate ticket for that third point but that seems like a very specific use-case that we may not be able to address here.

**Comment by benlk** [comment]
- [ ] If you edit the link's post and add a link to the description, does that appear in the description of the saved link, or is that removed by a filter?

Alternate ideas:

- text field thing where you highlight the section of the description of link and that becomes the link?
- shortcode flag to hide the title and make the entire description into a link

**Comment by aschweigert** [comment]
will need to look at html format for MWEN
