### ISSUE TITLE
README.txt needs header image and description needs work

### ISSUE THREAD

**Issue by rnagle** [INN/link-roundups#72]
We've got a decent start: https://wordpress.org/plugins/link-roundups/

But, we could stand to have [a little more flair](https://www.youtube.com/watch?v=_ChQK8j6so8).

**Comment by rnagle** [comment]
The plugin description needs to be less than 150 characters. We can use the [validator](https://wordpress.org/plugins/about/validator/) to make sure the readme meets WP's strict standards.

**Comment by dryanmedia** [comment]
See pull #87

**Comment by dryanmedia** [comment]
Header image needs to be thrown in /assets folder in svn
http://www.limecanvas.com/how-to-add-a-header-image-to-your-wordpress-org-plugins/

![lr-header](https://cloud.githubusercontent.com/assets/9565066/9360983/327252ec-464e-11e5-8e84-b88d64fb012f.jpg)

**Comment by kaeti** [comment]
I think we should make the link icon in the image a brand color. How about #FF8E46.

Also the blue. 1DC1F3

Let me know if that looks crazy.

**Comment by dryanmedia** [comment]
Ok here it is
![link_roundups_wporg_header-kaetifeedback](https://cloud.githubusercontent.com/assets/9565066/9444823/a0e49864-4a3d-11e5-97ba-2e31bd591b67.jpg)

**Comment by aschweigert** [comment]
let's go with that

**Comment by kaeti** [comment]
thumbsup

**Comment by dryanmedia** [comment]
The illustrator document that contains the original asset is in the Google Drive project folder for Link Roundups.

Note for future on those req's:
- 1544px by 500px for @2x
- JPG
- padding: 20px 30px for wordpress box shadow and spacing for title overlay.

**Comment by aschweigert** [comment]
@rnagle ok to close this?
