### ISSUE TITLE
Remove argo-* from code

### ISSUE THREAD

**Issue by dryanmedia** [INN/link-roundups#8]
Remove argo prefixes from code to avoid confusion.

**Comment by dryanmedia** [comment]
![screen shot 2015-06-19 at 7 44 57 am](https://cloud.githubusercontent.com/assets/9565066/8255896/17b83ae6-1658-11e5-8fa1-3454c54961ec.png)

**Comment by willhaynes** [comment]
While we're at it we should bundle the classes in `./classes/` and other includes in `./inc/`

**Comment by rnagle** [comment]
See #41.

**Comment by dryanmedia** [comment]
Places where argo still is as of now:
- On Saved Links there are Custom Meta that need migration
- Migrate argo-link-tags to saved-link-tags

**Comment by dryanmedia** [comment]
- [ ] left over argolinks_flush option deleted, accounted for and converted to transient
- [ ] taxonomy (in progress)
- [ ] post meta

**Comment by dryanmedia** [comment]
argolinks_flush fixed in #76 
taxonomy fixed in #83 
post meta fixed in #82
