### ISSUE TITLE
archive page for the saved links post type duplicates headlines

### ISSUE THREAD

**Issue by aschweigert** [INN/link-roundups#91]
See, for example: http://aspenjournalism-org.largoproject.staging.wpengine.com/rounduplink/

The headline should not be displayed both in the usual place AND as part of the link description. It should be one or the other. Also, the byline here is probably irrelevant (or maybe it should be the link source?)
![untitled](https://cloud.githubusercontent.com/assets/490703/9365804/90d56698-4681-11e5-9ac1-c494422a22af.png)

**Comment by dryanmedia** [comment]
Fixed in #93
