### ISSUE TITLE
Error notices

### ISSUE THREAD

**Issue by 0aveRyan** [INN/link-roundups#95]
I hadn't seen this in a little while on my host, but it's cropped up.

PHP 5.6 standard MAMP stack, WordPress 4.3
- Database update script returns console error and doesn't run
- Widgets display notice below instead of fields
- Errors print at top of Admin

Strict Standards: Non-static method Save_To_Site_Button::init() should not be called statically in /home/davidry0/public_html/wp-content/plugins/link-roundups/inc/lroundups/browser-bookmark.php on line 279

Notice: The called constructor method for WP_Widget is deprecated since version 4.3.0! Use
__construct()
instead. in /home/davidry0/public_html/wp-includes/functions.php on line 3457

**Comment by benlk** [comment]
> PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; saved_links_
> widget has a deprecated constructor in /nas/content/live/usenergynews/wp-content/plugins/link-roundups/inc/saved-links/class
> -saved-links-widget.php on line 7
> Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; saved_links_widge
> t has a deprecated constructor in /nas/content/live/usenergynews/wp-content/plugins/link-roundups/inc/saved-links/class-save
> d-links-widget.php on line 7
>

**Comment by benlk** [comment]
Also there's a use of `split()` which should be replaced with `explode()` or an equivalend.

**Comment by benlk** [comment]
Closing in favor of https://github.com/INN/link-roundups/issues/132, though that came second.
